name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hello, thanks for taking the time to create an issue. The developers of the repository will talk to you as soon as possible. Make sure you clearly explained the repro to the issue and what''s the expected and actual results you got.'
        pr-message: 'Congratulations on your first pull request. I encourage you to create more and more as you get involved. :+1: Thanks for taking the time to do so. It is greatly appreciated.'
